import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import { AuthProvider } from "./contexts/AuthContext";
import Navbar from "./components/Navbar";
import FilmGrain from "./components/FilmGrain";
import ThemeSwitcher from "./components/ThemeSwitcher";
import ChatBot from "./components/chatbot/ChatBot";
import ProtectedRoute from "./components/ProtectedRoute";
import AdminRoute from "./components/AdminRoute";
import AdminLayout from "./components/AdminLayout";
import Index from "./pages/Index";
import Login from "./pages/Login";
import FaceSwap from "./pages/FaceSwap";
import VoiceChanger from "./pages/VoiceChanger";
import Booking from "./pages/Booking";
import Settings from "./pages/Settings";
import Dashboard from "./pages/Dashboard";
import VideoTemplates from "./pages/VideoTemplates";
import AdminDashboard from "./pages/admin/AdminDashboard";
import AdminUsers from "./pages/admin/AdminUsers";
